Remove unused part in releasenotes template
istio/tools pull request #1874
Opened 2022-02-25 05:56 UTC by hanxiaop

/cc @brian-avery

2022-02-25 06:15 UTC, istio-testing commented
@hanxiaop: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
containers-test_tools | 86c7822617732198689bfbb7ce72ac28a270b407 | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/1874/containers-test_tools/1497088139582246912) | true | `/test containers-test_tools`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-25 06:35 UTC, hanxiaop commented
/test containers-test_tools

2022-02-28 18:25 UTC, ericvn requested changes
This is used in the release docs. See https://github.com/istio/istio.io/blame/master/content/en/news/releases/1.13.x/announcing-1.13.1/index.md#L14 for an example.

I note that one release is missing this tag.

2022-03-01 04:09 UTC, hanxiaop commented
@ericvn Thanks!

2022-03-01 04:09 UTC, closed without merging