Use bionic instead of xenial
istio/tools pull request #1932
Opened 2022-03-24 22:48 UTC by jacob-delgado

Envoy uses bionic to build, not xenial

See https://github.com/envoyproxy/envoy-build-tools/blob/f710be3099b65a2f260a632f8336a2c18e8324b9/build_container/Dockerfile-ubuntu#L13

2022-03-24 22:49 UTC, howardjohn requested changes
This is intentional to support users running Xenial/other old OS's. Unfortunately the underlying OS we build on impacts the compatibility due to GLIBC being horrible.

So this is a user facing deprecation - it may be a good idea but I think we need wider discussion.

Did I mention I hate GLIBC?

2022-03-25 07:12 UTC, jacob-delgado commented
At this point Ubuntu 16.04 requires a subscription to get extended security updates. It's basically EOL except for large enterprises that are paying for this.

We should drop support for this as purely open source shops are limited by this and it causes us pain when trying to upgrade. I'll put it on the agenda for the next meeting.

Thoughts @ericvn ?

2022-03-25 14:01 UTC, howardjohn commented
One thing to note is I think this will also drop debian 9 which is still in support for a few more months

2022-03-30 16:33 UTC, jacob-delgado commented
From the combined WG meeting:

> Plan: in 1.14 notes, give notice we will drop support unless there is feedback to do diferently

2022-03-30 16:36 UTC, jacob-delgado commented
Would this prevent CentOS 7 users from running Envoy in a VM directly? CentOS 7 EOL is in 2 years and it's highly used.

2022-03-30 16:41 UTC, howardjohn commented
Centos 7 is already incompatible with xenial

2022-07-21 03:02 UTC, closed without merging