Prevent injection vulnerabilities
istio/tools pull request #2141
Opened 2022-09-15 18:15 UTC by lei-tang

To prevent injection vulnerabilities, replace “text/template” with “[github.com/google/safetext](https://github.com/google/safetext)”.

2022-09-15 18:16 UTC, istio-testing commented
@lei-tang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
test_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/test_tools/1570476465307258880) | true | `/test test`
build_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/build_tools/1570476465164652544) | true | `/test build`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-15 18:17 UTC, istio-testing commented
@lei-tang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
test_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/test_tools/1570476465307258880) | true | `/test test`
build_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/build_tools/1570476465164652544) | true | `/test build`
gencheck_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/gencheck_tools/1570476465361784832) | true | `/test gencheck`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-15 18:17 UTC, istio-testing commented
@lei-tang: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
test_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/test_tools/1570476465307258880) | true | `/test test`
build_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/build_tools/1570476465164652544) | true | `/test build`
gencheck_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/gencheck_tools/1570476465361784832) | true | `/test gencheck`
lint_tools | de5c4fd52fa2ee19812381881622dfa866c83d9e | [link](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_tools/2141/lint_tools/1570476465202401280) | true | `/test lint`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-09-15 18:30 UTC, howardjohn requested changes

2022-09-15 18:30 UTC, howardjohn commented on isotope/convert/pkg/graphviz/graphviz.go
> +	template "github.com/google/safetext/yamltemplate"
this isn't yaml

2022-09-15 18:30 UTC, howardjohn commented on cmd/goc/template.go
> +	template "github.com/google/safetext/yamltemplate"
this isn't yaml

2022-09-15 18:30 UTC, howardjohn commented
I don't think this is solving any real problems - and actually introduces bugs

2022-09-16 00:21 UTC, lei-tang commented
Based on offline discussions, this PR is closed.

2022-09-16 00:21 UTC, closed without merging